---
title: "Shiny Application"
author: "Sadjad Zamani"
always_allow_html: true
output: 
  html_document:
    keep_md: true
---
```{r include=FALSE}
# some global options
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_knit$set(cache = TRUE)
knitr::opts_chunk$set(fig.path = "./figure/")
knitr::opts_chunk$set(fig.align = "center")
```


## Introduction
In this demo I want to plot the age demographics of different countries around the world.
I'm getting the data from [The World Bank](https://www.worldbank.org/en/home) using this [api](https://github.com/gshs-ornl/wbstats)


## Packages
```{r packages}
library(wbstats)
library(tidyverse)
library(ggplot2)
library(gganimate)
library(shiny)
```

```{r loadData}
if (file.exists("data.csv")) {
    df <- read_csv2("data.csv", show_col_types = FALSE)
} else {
    wb_search("population ages.*male")[1:5, ]
    # array of ["SP.POP.0004.FE" .. "SP.POP.2024.MA" .. ]
    indicators <- paste(rep(
        c(
            "SP.POP.0004", "SP.POP.0509",
            paste("SP.POP.", 5 * c(2:15), 5 * c(2:15) + 4, sep = ""),
            "SP.POP.80UP"
        ), 2
    ), c(".FE", ".MA"), sep = "")

    # to get the orginal data I used this command
    df <- wb_data(indicator = indicators, start_date = 2001, end_date = 2020)
}

# To save the regions in the dataframe
df <- left_join(
    df,
    wb_countries()[, c("iso3c", "region")],
    by = c("iso3c")
)

# Remove unneccesary columns
df <- df %>%
    relocate(region, .after = "country") %>%
    select(-c("iso2c", "iso3c")) %>%
    rename(year = date)
```

```{r}
df <- df %>%
    # look ath this example:
    # https://tidyr.tidyverse.org/reference/pivot_longer.html#ref-examples
    # making the table longer
    pivot_longer(
        cols = !c("country", "region", "year"),
        names_to = c("age", "gender"),
        names_pattern = "SP.POP.(.*).(..)",
        values_to = "population"
    ) %>%
    # making the gender as a factor
    mutate(gender = if_else(gender == "FE", "Female", "Male")) %>%
    mutate(gender = as.factor(gender)) %>%
    # making the age as a factor
    mutate(age = if_else(age == "80UP", "80+", age)) %>%
    mutate(age = paste(substr(age, 1, 2), "-", substr(age, 3, 4), sep = "")) %>%
    mutate(age = as.factor(age))
```
```{r}
regions <- unique(df$region)
countries <- df %>%
    select(region, country) %>%
    group_by(region) %>%
    distinct()

countries <- countries %>%
    group_split(.keep = FALSE) %>%
    setNames((group_keys(countries))$region)
```

```{r}
get_plot <- function(df, which_country = "Iran, Islamic Rep.", which_year = 2010) {
    total_population <- df %>%
        filter(country == which_country) %>%
        filter(year == which_year) %>%
        select(population) %>%
        summarise_all(sum)

    total_population <- round(total_population$population / 1000000, 0)

    g <- df %>%
        filter(country == which_country) %>%
        filter(year == which_year) %>%
        mutate(population = population / 1000) %>%
        mutate(population = ifelse(gender == "Male", population * (-1), population * 1)) %>%
        ggplot() +
        aes(x = age, y = population, fill = gender) +
        geom_bar(stat = "identity") +
        coord_flip() +
        labs(
            title = paste(
                "Population of", which_country,
                "(", which_year, ")",
                "[", total_population, " millions ]"
            ),
            x = "Age",
            y = "Population(in thousands)"
        ) +
        scale_y_continuous(labels = abs) +
        theme(
            legend.text = element_text(
                size = 15,
                face = "bold"
            ),
            plot.title = element_text(
                size = 22,
                hjust = 0.5,
                face = "bold"
            ),
            plot.subtitle = element_text(
                size = 14,
                hjust = 0.5,
                face = "bold"
            ),
            axis.title.x = element_text(
                size = 16,
                face = "bold"
            ),
            plot.caption = element_text(
                size = 12,
                hjust = 0.5,
                face = "italic",
                color = "gray"
            )
        )
    # g +
    # transition_states(
    # year,
    # transition_length = 2,
    # state_length = 1
    # ) +
    # ease_aes("sine-in-out")
    # anim_save(paste("animations/", which_country, ".gif", sep = ""))
    g
}
```


```{r shinyUI}
# Define UI for random distribution app ----
ui <- fluidPage(

    # App title ----
    titlePanel("Tabsets"),

    # Sidebar layout with input and output definitions ----
    sidebarLayout(

        # Sidebar panel for inputs ----
        sidebarPanel(
            # Input: Select the region from this list
            selectInput(
                inputId = "region",
                label = "Region:",
                choices = regions,
                selected = "Middle East & North Africa"
            ),
            br(),

            # Input: Select a country from this region
            selectInput(
                inputId = "country",
                label = "Country:",
                choices = countries[["Middle East & North Africa"]],
                selected = "Iran, Islamic Rep.",
            ),
            br(),

            # Input: Slider for the year
            sliderInput(
                inputId = "year",
                label = "year",
                value = 2010,
                min = 2001,
                max = 2020,
                step = 1,
            )
        ),

        # Main panel for displaying outputs ----
        mainPanel(

            # Output: Tabset w/ plot, summary, and table ----
            tabsetPanel(
                type = "tabs",
                tabPanel("Plot", plotOutput("plot")),
                # tabPanel("Summary", verbatimTextOutput("summary")),
                # tabPanel("Table", tableOutput("table"))
            )
        )
    )
)
```
```{r shinyServer}
# Define server logic for random distribution app ----
server <- function(input, output, session) {
    observe({
        x <- input$region
        y <- c(countries[[x]]$country)

        # Can also set the label and select items
        updateSelectInput(
            session,
            inputId = "country",
            choices = y,
            selected = input$country
        )
        print(paste("Region :", x, ", Country: ", input$country, "(", input$year, ")"))
        output$plot <- renderPlot(get_plot(df, input$country, input$year))
    })
}
```

```{r shinyApp}
shinyApp(ui, server)
```
